# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"


  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions

 build_ios_app(
      configuration: "Debug",
      scheme: "Release",
      clean: true,
      export_method: 'app-store',
      export_options: {
      provisioningProfiles: { 
        "com.ibsplc.ems.tech" => "Tech360Profile_Adhoc.mobileprovision"
      }
    },
      output_directory: "~/Desktop",
      output_name: "snowfinchApp.ipa"
    )
    upload_to_testflight(username: 'krishnapriya.radhakrishnan@ibsplc.com')
  end

end
